version: '3.5'

services:
  db:
    image: postgres:13
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_DB=irb3
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
